# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b558b585d4f586210a335fed1a354aec95a2be6b5ce7fe8966bcb364ac934a6c4d4900b8a0ebc1dcd17a5c18c7ba13befe91c73ec6c853aa4c065c128ad176

test:
  secret_key_base: 43cc8caeb9b41d7f184ccdfc000703c05553078279ebbdadd47e79eb43829e039dd8e22b5fa045679e274a29434dac3c1882bb6e98f8913697a98890a6a1e902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
